### ISSUE TITLE
Support for ownCloud News app

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#12]
[ownCloud](http://owncloud.org) also has a News reader app with an API: https://github.com/owncloud/news/wiki/API-1.2 – if you have more questions, @Raydiation and @zimba12 are the developers.

Would be cool if FeedMonkey would support that as well since ownCloud gets more and more widespread. You can see some screenshots of the app at http://apps.owncloud.com/content/show.php/News?content=158434

**Comment by jeena** [comment]
Ah I wasn't aware of that, I will have a look at it, didn't think about supporting other APIs yet but could be a good thing.

**Comment by jeena** [comment]
I have started to work on the ownCloud integration but I found some problems which prevent me of implementing everything yet, we are trying to extend the API in that regard, you can follow the discussion on https://github.com/owncloud/news/issues/354

**Comment by jancborchardt** [comment]
Wohoo, awesome to see that collaboration! :) Looking forward to it

**Comment by jeena** [comment]
Ok, I have been able to work around the issues so FeedMonkeys next version will be compatible with the normal ownCloud News app.

It would be cool if for example you @jancborchardt could beta test it before I push it to the marketplace.

**Comment by jancborchardt** [comment]
Wow, awesome! How can I beta test it - do you have a dev deployment running
somewhere? (I can recommend http://5apps.com by the way)

**Comment by cosenal** [comment]
@jeena Awesome to see this collaboration!!!

@jancborchardt I use FirefoxOS simulator https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/

So far it works! I will report bugs/try to help with the code.
Thanks for this!

**Comment by jeena** [comment]
Ok thanks for testing it, I will zip it now and send it to the Marketplace.

@jancborchardt 5apps.com looks interesting but I don't need to host it myself right now, it is hosted by the Firefox Marketplace. You can always use the zip github provides which you can find in the right sidebar on the main page of this repository. Because it doesn't need to be compiled you can use it directly in your Firefox OS simulator.

**Comment by jancborchardt** [comment]
When trying it with my ownCloud installation, I get an »error: 0« alert at the log in screen, and a 404 for `OPTIONS https://[my server]/index.php/apps/news/api/v1-2/version`

Any idea @Raydiation @zimba12 @jeena?

**Comment by jancborchardt** [comment]
@jeena hosting it is useful to make it platform-independent, so people could also use it on iOS devices. Since you already use Github, you could use Github Pages as a staging platform also: Just create a »gh-pages« branch and use that instead of »master« – the contents of that branch will show up at http://jeena.github.io/FeedMonkey (you probably know that already since you use Github Pages. :)

**Comment by jeena** [comment]
@jancborchardt it looks like you're either not giving it the right URL (perhaps http instead of https or a different directory or subdomain). Therefor it can't find it. Do you have installed the News app in ownCloud and is it working?

About the hosting, the problem is that TinyTinyRSS doesn't support CORS (and I did get quite some [beating while asking for that](http://tt-rss.org/forum/viewtopic.php?f=8&t=2551) so I gave up), therefor there was no way for me to get it working on iOS or Android like that. On Firefox OS I am able to make it a privileged app which is allowed to do cross origin requests. I will look into other backends like feever and feedly too, if I get more working with CORS then I probably will make it a hosted one.

**Comment by jancborchardt** [comment]
Whoops, nevermind – I just forgot the /owncloud subdirectory ;) Works now, but the error message could still be better, see https://github.com/jeena/FeedMonkey/issues/15 :)

And wow @jeena, that TinyTinyRSS discussion thread really is ugly. Good on you for supporting more different platforms. Oh and just a note about Android: Any Firefox Marketplace app can be installed on Android as well, you just need to use the Firefox Beta browser.

**Comment by BernhardPosselt** [comment]
@jancborchardt yeah, the ttrss devs are dicks. Had to deal with them too.

**Comment by jancborchardt** [comment]
@Raydiation @zimba12 make sure to rate FeedMonkey on the Firefox Marketplace too :) https://marketplace.firefox.com/app/feedmonkey

**Comment by jancborchardt** [comment]
By the way, retweet this announcement everyone! :) https://twitter.com/ownClouders/status/391482603670228992

**Comment by danc** [comment]
Hi !
Thanks for the great work, and good idea.
I still have an 'Error 0' when trying to enter owncloud credentials. (under FFOS simulator)
https://[domain]/owncloud/
My domain has 3 parts, like toto.eu.com
I have a self signed certificate. May it be related ?
Owncloud version : 5.0.12 
News version 1.605

**Comment by jeena** [comment]
Hi Danc,

Would it be possible to make a new account for me on this server so I could test it? You can send me the credentials to info@jeenaparadies.net

**Comment by jeena** [comment]
Ah, yes, the self signed certificate is most probably the problem. I'm not sure how to fix it yet.
